services:
  # localstack:
  #   container_name: localstack
  #   image: localstack/localstack:4.9.1
  #   ports:
  #     - "127.0.0.1:4566:4566" # LocalStack Gateway
  #     - "127.0.0.1:4510-4559:4510-4559" # external services port range
  #   environment:
  #     # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
  #     - DEBUG=0
  #   volumes:
  #     - "./volume/localstack:/var/lib/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   networks:
  #     - playground

  postgres-backend:
    container_name: "postgres-backend"
    image: postgres:18.1-trixie
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: backend
      POSTGRES_PASSWORD_FILE: /run/secrets/backend_db_secret
    volumes:
      - pg_backend_data:/var/lib/postgresql
    networks:
      - playground
    secrets:
      - backend_db_secret

  postgres-keycloak:
    container_name: "postgres-keycloak"
    image: postgres:18.1-trixie
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD_FILE: /run/secrets/keycloak_db_secret
    volumes:
      - pg_keycloak_data:/var/lib/postgresql
    networks:
      - playground
    secrets:
      - keycloak_db_secret

  keycloak:
    container_name: keycloak
    build: ../keycloak-custom
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: info

      KC_SPI_EVENTS_LISTENER_USER_EVENT_LISTENER_NATS_URL: nats://nats:4222
    ports:
      - "7777:8080"
    networks:
      - playground

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.11
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_admin_secret
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - playground
    secrets:
      - pgadmin_admin_secret

  nats:
    container_name: nats
    image: nats:2.12.3-alpine
    command: ["-js", "-sd", "/data", "--http_port", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - playground
    volumes:
      - nats_data:/data

volumes:
  pg_backend_data:
  pg_keycloak_data:
  pgadmin_data:
  nats_data:

networks:
  playground:

secrets:
  backend_db_secret:
    environment: BACKEND_DB_PASSWORD
  keycloak_db_secret:
    environment: KEYCLOAK_DB_PASSWORD
  pgadmin_admin_secret:
    environment: PGADMIN_ADMIN_PASSWORD
