services:
  # localstack:
  #   container_name: localstack
  #   image: localstack/localstack:4.9.1
  #   ports:
  #     - "127.0.0.1:4566:4566" # LocalStack Gateway
  #     - "127.0.0.1:4510-4559:4510-4559" # external services port range
  #   environment:
  #     # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
  #     - DEBUG=0
  #   volumes:
  #     - "./volume/localstack:/var/lib/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   networks:
  #     - playground

  postgres-keycloak:
    container_name: "postgres-keycloak"
    image: postgres:18.1-trixie
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - "./volume/postgres-keycloak:/var/lib/postgresql"
    networks:
      - playground

  keycloak:
    container_name: keycloak
    build: ../keycloak-custom
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://postgres-keycloak:5432/keycloak"
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info

      KC_SPI_EVENTS_LISTENER_USER_EVENT_LISTENER_NATS_URL: nats://nats:4222
    ports:
      - "7777:8080"
    networks:
      - playground

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.11
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./volume/pgadmin:/var/lib/pgadmin
    networks:
      - playground

  nats:
    container_name: nats
    image: nats:2.12.2-alpine
    command: ["-js", "-sd", "/data", "--http_port", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - playground
    volumes:
      - ./volume/nats-data:/data

networks:
  playground:
